### ISSUE TITLE
color markers performance

### ISSUE THREAD

**Issue by veksha** [veksha/cuda_exterminal#1]
@Alexey-T, Hi. This is terminal emulator that can be better then Terminal+. This is work in progress, some bugs are present.
But the main thing that I want to deal with right now is colorizing speed.

I think this line is slowing down plugin a lot:
```python
self.memo.attr(MARKERS_ADD, x=x, y=y, len=1, color_font=fg, color_bg=bg, font_bold=bold)
```

if this line somehow can be optimized in pascal code -> GOOD.
If not, we can think of another API that will be capable to colorize faster then markers.

try for yourself.
make sure you enable **colors** in config!
notice how without colors it's pretty fast, but colors slow down a lot.

**Comment by veksha** [comment]
you can use colortest files that is included inside its directory.
also notice that while adding markers is very slow, the speed of rendering colors is fine, i think.

**Comment by veksha** [comment]
I will try and report, thanks!

**Comment by veksha** [comment]
tried MARKERS_ADD_MANY, not useful, because I need per character markers with different colors.
MARKERS_ADD_MANY accepts lists for x/y/len but not for color_font/color_bg/font_bold.

**Comment by Alexey-T** [comment]
Improved the API. see https://github.com/Alexey-T/CudaText/commit/9f8b919c402b168b10ba25594780bb91243c65dd

tested only a little:
![Screenshot from 2022-07-07 10-29-18](https://user-images.githubusercontent.com/4154978/177718544-2fb3f16c-f601-40a2-a06b-db02411e9d0c.png)

**Comment by veksha** [comment]
One little thing.. I need font_bold, not color_border.

**Comment by Alexey-T** [comment]
font_bold / font_italic / font_strikeout also can be lists.

**Comment by veksha** [comment]
awesome!

**Comment by veksha** [comment]
MARKERS_ADD_MANY increased perofmance a little. I see it while running 256test.sh
BUT main speed up is from removing MARKERS_DELETE_BY_POS.

I don't know if I should delete markers now. maybe let them be.

**Comment by veksha** [comment]
please test latest changes

**Comment by Alexey-T** [comment]
last changes: colors are disappeared. hm..

**Comment by veksha** [comment]
what markers are you talking about? URL markers?

**Comment by Alexey-T** [comment]
about `attr` markers in the ExTerm's memo editor.

**Comment by veksha** [comment]
paste into console: `app_api_version()`

**Comment by Alexey-T** [comment]
ignore last complain-- colors ok

**Comment by Alexey-T** [comment]
I mean “other color attributes”. Why do you need api markers_delete_by_pos if you can clear all attrs?

**Comment by veksha** [comment]
I can't clear all attrs, history lines will lose their colors.
i'm not adding colors to whole memo on every memo_update. (it would be expensive). only to dirty(changed) lines. color of others must stay.

**Comment by veksha** [comment]
memory consumption is increased by removing MARKERS_DELETE_BY_POS, (kind of memory leak)
but speed in increased massively.

if MARKERS_DELETE_BY_POS can't be optimized, maybe MARKERS_DELETE_BY_LINE (if it would exist) can be faster?
if not, let's leave it like this, i guess.

**Comment by Alexey-T** [comment]
MARKERS_DELETE_BY_POS can be called with y=-1 to delete for line.

**Comment by veksha** [comment]
i will try it

**Comment by Alexey-T** [comment]
Re-used 'binary search' in TATSynEdit markers DeleteByPos , pls pull and test again.

**Comment by Alexey-T** [comment]
> delete old marker on insertion of a new

must be already like this. no?

**Comment by veksha** [comment]
"Duplicate fragments, ie with the same (x, y) pair, are allowed. Last added fragments go to the later indexes, and all fragments are painted in their order in the fragment list, so last added fragments are painted over previous ones."

they can be different in style. on fragment is bold, second is red, etc...

**Comment by Alexey-T** [comment]
added API to control 'dups' flag!
try from source.
https://github.com/Alexey-T/CudaText/commit/eff397101c7a230c4a8e7f328bbc94fd51398108

**Comment by veksha** [comment]
i think MARKERS_DELETE_BY_POS with new search is faster, but grows slower with new lines/markers, nevertheless.

**Comment by veksha** [comment]
`self.memo.attr(MARKERS_SET_DUPS, tag=0)`
yes, this slows down with every `sh 256test.sh` call.

**Comment by Alexey-T** [comment]
it deleted dups only if x/y are the same, but it don't delete dups if they overlap with different x/y.
are you sure you pass the same x/y?

**Comment by veksha** [comment]
it is interesting why adding new marker is fast, but deleting is slow.

**Comment by Alexey-T** [comment]
made fix no.2.
also we can test contents of attrib-list - using `markers(MARKERS_GETxxx)` and seeing if it has trash items.

**Comment by veksha** [comment]
> it deletes dups only if x/y are the same, but it don't delete dups if they overlap with different x/y. are you sure you pass the same x/y?

yes, same x/y/ len=1
removing dups are important when you are refreshing the same lines. for example: launch `nano` and keep pressing F1. the same lines will be refreshed (adding new markers at same positions).
but when memo line count is low (and marker count is low) removing dups is a fast operation.

**Comment by Alexey-T** [comment]
#27 - answered...

**Comment by Alexey-T** [comment]
Made new optim in Markers.Add for the case dups=on. Pls pull atsynedit again.

**Comment by veksha** [comment]
Thank you. I think this is resolved. nice!
