### ISSUE TITLE
Bash path must be the option

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_exterminal#11]
e.g. on linux it cann be '/bin/bash/ and /usr/bin/bash'.

Also, BSD systems and MacOS need their separate option, different from Linux one

"shell" for Windows
"shell_linux"
"shell_macos"
"shell_freebsd"
"shell_openbsd"
"shell_netbsd"
"shell_dragonfly"

**Comment by Alexey-T** [comment]
API may help you:
app_proc(PROC_GET_OS_SUFFIX, '')

**Comment by veksha** [comment]
if i'm not mistaken - all BSD's are unixes (or unix-like rather). so `shell_unix` could be sufficient?

**Comment by Alexey-T** [comment]
okay, shell_unix but macOS is different - good to have shell_macos with high prior. macOS may have totally different path to Bash

**Comment by veksha** [comment]
what do you mean by `high prior`?

also path is not important, i think:
in Terminal+ we see:
```
shell_windows=cmd.exe
shell_unix=bash
shell_macos=bash
```

so it doesn't matter where is it. it will be called if it's in a PATH.

**Comment by Alexey-T** [comment]
Ok, so option is not needed.

**Comment by Alexey-T** [comment]
Ok, it can be like in Terminal+

(high priority - I mean shell_unix must be read _after_ shell_macos)

**Comment by veksha** [comment]
why we need to read shell_unix in macos?

```
IS_MAC = sys.platform=='darwin'
```

just check and read `shell_macos`. ignore shell_unix.
?

**Comment by Alexey-T** [comment]
yes, you are right.

**Comment by Alexey-T** [comment]
is it implemented already, I cannot find the code?
