### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by veksha** [veksha/cuda_exterminal#13]
@Alexey-T
Given that we already have icons near bottom panel the tabs feature is not really necessary.
Also, floating mode can be removed too, because we can toggle floating mode of the whole bottom panel.

I'm trying to follow KISS principle. And I want to hear your point of view. What is the Cud's way.
Why Terminal+ implemented "tabs statusbar" and floating mode when all functionality was already present in Cud.

I mean:
 - tabs = icons in bottom panel
 - floating mode = floating bottom panel.

**Comment by Alexey-T** [comment]
- floating mode was made by me, in simple plugin. then it was inherited. in Term+. maybe i thought it was usefull at those times?
- tabs are not needed, for me. tabs were designed by Term+ author.

**Comment by veksha** [comment]
I guess i just need to make "ExTerminal: Spawn new terminal" command + refactor the code to support multiple instances and that's all.
What is your workflow? do you need automatic spawning/switching dir functionality?

**Comment by Alexey-T** [comment]
- i need to call Term plugin to open tern in the dir of the focused file
- then i do stuff. then i don't need that term anymore (with that cwd)

**Comment by veksha** [comment]
added new commands:
 - New terminal
 - Close all terminals
 
limited number of terminals to 4
because when there is a lot of fast timers with "sleep" inside -> Cud can appear frozen.
sleep inside timer needed to give cpu time to worker thread. I don't know how to efficiently balance python threads. Maybe there is a way to do it without timers...

**Comment by Alexey-T** [comment]
new commands work good. Thanks.
suggestion-- if I have focused terminal , and I call "close all terminals", put focus to editor.

can I publish this in addons?
