### ISSUE TITLE
hanged here, with colors=1, when I do 'ls -l /usr/bin'

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_exterminal#20]
Ubuntu 20.4 x64
even Cud's cursor stopped blinking.

![Screenshot from 2022-07-05 22-30-58](https://user-images.githubusercontent.com/4154978/177401953-df977233-3fe7-4e78-abd2-fc37ff322d03.png)

**Comment by Alexey-T** [comment]
hanging is reproducible.

**Comment by Alexey-T** [comment]
with colors=0 it works!

**Comment by veksha** [comment]
just wait. it is working :D

it is MARKERS_ADD issue.
I will replace it with MARKERS_ADD_MANY soon.

related issue: #1
