### ISSUE TITLE
thanks and suggestions…

### ISSUE THREAD

**Issue by MiroslavMatas** [veksha/cuda_exterminal#23]
Hi Yuriy! (Юрий!)
**looks promising!** very promising : - )
a few suggestions (not so critical, sure…), as potential enhancements…
• run selection from editor
• run current tab/file at exterminal
• shortcut for switch focus between exterminal and editor

**Comment by veksha** [comment]
Hi, Miroslav.
what do you mean by "run current tab/file at exterminal"?
paste full file path and send Enter key? or just paste without sending Enter?

**Comment by MiroslavMatas** [comment]
> paste full file path and send Enter key? 

exactly

**Comment by veksha** [comment]
added new commands, please test.

**Comment by MiroslavMatas** [comment]
do I need to wait some time for offering update? (Addon Manager do not see 2022.07.07…)
and manual uninstall/restart/install lead to 2022.07.06 - tested a few times…

**Comment by MiroslavMatas** [comment]
install from ZIP - lead to new/updated build 2022.07.07… 
but!
Addon Update is not ok
![image](https://user-images.githubusercontent.com/42316770/177702497-e6093cf8-2260-4e94-b5a4-e624c559be68.png)

**Comment by MiroslavMatas** [comment]
… and - we must to cover full path including space characters
![image](https://user-images.githubusercontent.com/42316770/177702756-e7c29349-5723-41b9-920c-b37f175aa769.png)

**Comment by veksha** [comment]
use "Install from Git..." command if you want to pull latest changes or wait for Alexey to update it.

**Comment by veksha** [comment]
https://github.com/veksha/cuda_exterminal/commit/6c3de2d5d799f00500bc8ad7729f563ca3081f1f
added double-quotes, please try again.

**Comment by MiroslavMatas** [comment]
works fine now, thanks a lot…
_toggle focus_ is ok
_run current fine_ is ok

but wait! : - )
_run selection_ on multiline selection… hmmm…
![image](https://user-images.githubusercontent.com/42316770/177706659-0907090d-e2cb-45ca-a686-28d4ad1fd83f.png)

**Comment by veksha** [comment]
fixed https://github.com/veksha/cuda_exterminal/commit/61c9df6880babf0205242ff227e9ec1082d5e989

**Comment by MiroslavMatas** [comment]
ok now
appreciate it

**Comment by veksha** [comment]
thank you for testing
