### ISSUE TITLE
URL markers

### ISSUE THREAD

**Issue by veksha** [veksha/cuda_exterminal#29]
Hi, @Alexey-T

I want ExTerminal to support URLs underline. they are working already, but in colorful mode underlined style is covered by my custom markers. I know that URL markers (id=-100) can't be removed, and it's okay, I want their underlined style to be on top of other attribs.

look at screenshot. only the first letter is underlined. (maybe it is covered by custom marker with len=1 and its len resized to 1? just a guess.)
without colors underline is ok for all letters.

![image](https://user-images.githubusercontent.com/275333/177976408-3be0b78e-6a6f-4c9a-8427-b505ca247dbd.png)

**Comment by Alexey-T** [comment]
1. can you detect all lines beginning with 'https://' , 'http://' and skip adding attr's there (at least until the first space)?

2. can you see the result of memo.attr(MARKERS_GET) to see what attribs you have for http line?

**Comment by Alexey-T** [comment]
3. consider to disable URLs, `PROP_LINKS_SHOW: bool: enable hyperlinks underlining.`

**Comment by veksha** [comment]
```python
ed.attr(MARKERS_SET_DUPS, 0)
ed.attr(MARKERS_GET)
ed.attr(MARKERS_ADD, x=1, y=0, len=36, color_font=0xFF)
ed.attr(MARKERS_GET)
```

![image](https://user-images.githubusercontent.com/275333/177978600-4e42d7ae-c85a-45f5-b629-4dcd30f40b62.png)

**Comment by veksha** [comment]
> 3. consider to disable URLs, `PROP_LINKS_SHOW: bool: enable hyperlinks underlining.`

I know that I can disable them. Why disable? they are pretty.

**Comment by veksha** [comment]
maybe markers with id=-100 can be on top of others? painted last?

**Comment by Alexey-T** [comment]
Ok, test shows 2 markers in list. 2nd one is from x=1, and it;s painted as second, over old URL marker. it is ok.

**Comment by Alexey-T** [comment]
> maybe markers with id=-100 can be on top of others? painted last?

it cannot be painted last - it;s start is smaller pos!

**Comment by veksha** [comment]
custom marker can't be inserted at pos x=0, because URL(id=-100) marker is there already. and it can't be replaced.
I wish there was a way to make it be painted last somehow so it can blend in beautifully.

**Comment by Alexey-T** [comment]
because I dont want to mess with markers painting order, sorry, it's hard part!

**Comment by veksha** [comment]
basically I need to do MARKERS_GET, then store all URL ranges in a list, then.. compare..
no need to detect "https://", they are all detected already and will always have -100 id. right?

**Comment by veksha** [comment]
commit: https://github.com/veksha/cuda_exterminal/commit/bc1c93506da6aa51359aab1d94f2a1b7402587ce
now URL markers are colored/underlined properly.
but only when they are on a single line.
I don't see a nice quick way to color/underline multilined URLs.

Maybe you, @Alexey-T, have an idea.

**Comment by Alexey-T** [comment]
what is example text wiith multi-line URL?

**Comment by Alexey-T** [comment]
found it--

![u](https://user-images.githubusercontent.com/4154978/178143642-7b30b1a8-c2f9-41ec-a9fa-237f79a6bd63.png)

**Comment by veksha** [comment]
insert long url into terminal or make small window so URL will wrap.
![image](https://user-images.githubusercontent.com/275333/178143660-a4ed78f3-d3af-4eee-8295-468bf6df1a62.png)

**Comment by Alexey-T** [comment]
is this planned to change? or let's close? @veksha

**Comment by veksha** [comment]
let's close for now
