### ISSUE TITLE
macOS testing

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_exterminal#33]
maybe @jairomartinezA can test this plugin on macOS? 
If not, I will test it on my old macbook, in few weeks.

**Comment by veksha** [comment]
![Screen Shot 2022-07-14 at 5 24 42 PM](https://user-images.githubusercontent.com/275333/179131461-01083d45-c594-4d0d-a483-3f5aa017eeaf.png)

**Comment by JairoMartinezA** [comment]
Sorry Alex

I had to change from Mac to W10 (Bootcamp) because I am over a development and I forcible need to use W10.

**Comment by Alexey-T** [comment]
I see it is OK under Mac. thanks
