### ISSUE TITLE
cannot copy contents of the memo

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_exterminal#34]
for the wiki
https://wiki.freepascal.org/CudaText_plugins#Terminal
I wanted to copy/paste terminal memo contents.
i select it here but plugin resets the selection!

![Screenshot_2022-07-22_17-18-54](https://user-images.githubusercontent.com/4154978/180459056-8ab975e7-fcbc-4ae0-8094-6118d803329d.png)

**Comment by Alexey-T** [comment]
any other way to copy memo-text? maybe add a command?

**Comment by veksha** [comment]
there are some tricks to make selection stay:
1. double-click and drag. selection will stay;
2. single-click and drag, do not release left button, press right button. selection will stay.

(to get rid of spaces I need to add this feature, but for now just paste text to new tab and use "trim spaces" from Command palette)


Terminals have abilty to make selections using mouse **without moving caret**.
can you, @Alexey-T, add this feature to API?

**Comment by Alexey-T** [comment]
can you add this info (1. and 2.) to readme.txt, please.

**Comment by Alexey-T** [comment]
>Terminals have abilty to make selections using mouse without moving caret.
can you, @Alexey-T, add this feature to API?

selection are existing only as part of carets, sorry.

**Comment by veksha** [comment]
added new feature:
- selected text is now copied to clipboard automatically (trimming trailing whitespace)
also you will see message in status bar that text was copied.

![image](https://user-images.githubusercontent.com/275333/180481829-bb865e35-6b22-4683-8084-87771be9864a.png)

**Comment by Alexey-T** [comment]
Good, thanks...
