### ISSUE TITLE
Windows/Linux discrepancies

### ISSUE THREAD

**Issue by veksha** [veksha/cuda_exterminal#35]
Hello @Alexey-T.
ExTerminal (or CudaText) has two issues.

1. on Cud startup focus goes to Editor on Windows (not to opened ExTerminal), but on Linux it goes to ExTerminal (which is bad).
   (PROC_BOTTOMPANEL_ACTIVATE api behaves differently on Windows/Linux?)
2. on Windows when I press any hotkey, for example `ctrl-shift-p` while ExTerminal is focused, this hotkey will not go outside of ExTerminal and nothing will happen, but on Linux it goes to main CudaText Window and invokes Command palette.
(on_key_press, on_key_down behaves differently on Windows/Linux?)

**Comment by Alexey-T** [comment]
1. Need to think
2. Hotkey only for top menu item? I understand it - handling of top menu hotkeys is built in in Lazarus. If you want to ignore some hotkey , try to handle it in on_key

**Comment by Alexey-T** [comment]
trying to repeat the 1) but Cud always starts with Console active - even if I activate 'ExTerminal 1' , after restart Cud don't show ExTerminal! do you see it?

**Comment by Alexey-T** [comment]
plugins.ini
```
[exterminal]
shell_windows=cmd.exe
shell_unix=bash
shell_macos=bash
colors=1
esc_focuses_editor=1
show_caption=0
```

**Comment by veksha** [comment]
> trying to repeat the 1) but Cud always starts with Console active - even if I activate 'ExTerminal 1' , after restart Cud don't show ExTerminal! do you see it?

no. "ui_bottom_on_start" option is not set to default?

**Comment by Alexey-T** [comment]
It was '0' which is default! after removing line in user.json - all works again. will see it.

**Comment by Alexey-T** [comment]
found the  reason - bug was visible IF session didn't have ui-tabs... fixed.

**Comment by Alexey-T** [comment]
@veksha 

>on Cud startup focus goes to Editor on Windows (not to opened ExTerminal), but on Linux it goes to ExTerminal (which is bad).

cannot see it here!
focus goes to editor. linux gtk2 version.

try on clean Cud with only ExTerminal, pls.

**Comment by veksha** [comment]
gtk2: OK
qt5: BAD

I tend to always use qt5 version of CudaText.
don't know why. maybe because it is not as old as gtk2? (2011 vs 2020)

**Comment by Alexey-T** [comment]
qt5 has good Laz maintainer. if we find bug there, its better.
looking.

**Comment by Alexey-T** [comment]
looked. qt5 version - also all OK here. I cannot see initially focused terminal.

**Comment by Alexey-T** [comment]
some steps  on clean Cud with ExTerm?

**Comment by veksha** [comment]
oh, it's because I have maximized window.
it happens on resize.

**Comment by Alexey-T** [comment]
let's create Cud issue?

**Comment by veksha** [comment]
> let's create Cud issue?

I'm starting to think it's a ExTerminal bug. (I have `on_resize` event)

Although it is interesting how gtk and qt behaves differently when maximized at startup.
but when I resize window it behaves similarly on both gtk and qt.

**Comment by Alexey-T** [comment]
> how gtk and qt behaves differently

usual situation.

**Comment by veksha** [comment]
let's talk about second issue:

> 2. Hotkey only for top menu item? I understand it - handling of top menu hotkeys is built in in Lazarus. If you want to ignore some hotkey , try to handle it in on_key_down

consider this situation on Linux:
1. set hotkey in Cud so `F10` key will open `Options Editor Lite`
2. focus ExTerminal, press `F10`
3. OEL will show up. even though I have `return False` in `form_key_down`:

```python
elif key == keys.VK_F10:
      self.write(ctrl.ESC+'[21~')
      return False
```

from wiki: `If plugin returns False, key is blocked.`

on Linux it is not blocked whether you return True or False or None.
on Windows it is **always** blocked.

maybe this happens for bottom panels only?

**Comment by Alexey-T** [comment]
not for bottom panels only- for all controls on a form. happens when 'hotkey accelerator' is set in the MainMenu (top menu bar). so - key goes to MainMenu handler before our 'on_key_down' . sad!

**Comment by Alexey-T** [comment]
so can I help more?

**Comment by veksha** [comment]
can be some bug in lazarus (difference between win/qt/gtk versions).
it would be good to check if we can make some workaround in pascal code to make uniform behaviour for all systems/backends.

**Comment by Alexey-T** [comment]
* PROC_SIDEPANEL_ACTIVATE: Activates tab. Returns bool: tab was found/activated. Param "text" can be string or tuple:
** str: caption.
** 2-tuple (caption, bool_set_focus). Default for bool_set_focus is False.

maybe plugin can be changed to call _ACTIVATE with bool_set_focus=False ?
```
    def show_terminal(self, t):
        app_proc(PROC_BOTTOMPANEL_ACTIVATE, t.name)
```

**Comment by Alexey-T** [comment]
quickly looked at app. cannot find the reason why 'memo' is focused. will try to create pascal demo for me.

**Comment by veksha** [comment]
i'm talking about hotkey issue. focus issue can be fixed in plugin, i think.

**Comment by Alexey-T** [comment]
Hotkey handling by MainMenu is heavy issue, seems not solvable by me (and we have macOS)

**Comment by Alexey-T** [comment]
About focusing issue. made some digging.
I placed 'breakpoint' in IDE on EditorFocus() in unit proc_editor.
qt5 version.

- if app not maximized, its called only 1 time on start - for the main editor tab
- if app maximized (in prev session), its called 2nd time - not from some Py code! becase 'stack trace' window shows it like its called from `api_ed_focus()`.

To find from WHAT Py code it was called (2nd time) i need to make some printing of stack-trace of Py code in cudatext.py.

**Comment by Alexey-T** [comment]
I dont know how to use this
https://docs.python.org/3/library/traceback.html

**Comment by Alexey-T** [comment]
ok, digged this more. added to cudatext.py to `def focus`:
```
    def focus(self):
        print(traceback.print_stack())
        return ct.ed_focus(self.h)
```

this shows that ExTerm is culprit!
```
Python 3.8.10
Init: cuda_exterminal
Init: cudatext
Startup: 450ms, plugins: 40ms (exterminal 43ms)
  File "/home/user/.config/cudatext/py/cudatext.py", line 1172, in _timer_proc_callback_proxy
    return _live[info](tag)
  File "/home/user/.config/cudatext/py/cuda_exterminal/terminal.py", line 432, in terminal_resize
    self.screen.resize(self.visible_lines,self.visible_columns-3)
  File "/home/user/.config/cudatext/py/cuda_exterminal/memoscreen.py", line 74, in resize
    self.memo.focus() # handy, but can be annoying to some
  File "/home/user/.config/cudatext/py/cudatext.py", line 1348, in focus
    print(traceback.print_stack())
None
```

**Comment by veksha** [comment]
thank you for investigation!

**Comment by veksha** [comment]
``` python
self.memo.focus() # handy, but can be annoying to some
```
it was added to make terminal focused after MANUAL resizing of bottom panel.
and on Windows and Linux-gtk it was playing fine with maximized window on app startup.

but qt5 version calling on_resize event even on initial maximized state on startup.

I guess I will just disable this code for now.
thanks again!

**Comment by veksha** [comment]
resizing of bottom panel is triggered even on manual resizing of the whole window. (obviously)
so this code is bad anyway.

**Comment by Alexey-T** [comment]
yes
