### ISSUE TITLE
Lexer: PAX_Pascal

### ISSUE THREAD

**Issue by veksha** [veksha/cuda_exterminal#36]
when opening .pas file, CudaText tells that it can download PAX_Pascal lexer for this file.
but when you agree and install, it will not be added to lexer list.
I don't know what is PAX but i assume that at least it must be shown in lexer list after installing.

**Comment by Alexey-T** [comment]
I see 'PAX pascal' is used only by silent ppl, I just removed it from 'lexer detecter' database. Cud will not suggest it.

**Comment by veksha** [comment]
sorry, opened issue in cuda_exterminal by mistake.

**Comment by Alexey-T** [comment]
reason for not showing: Internal field!
```
  LexerName = 'PAX Pascal'
  Internal = True
  Charset = DEFAULT_CHARSET
end
```

**Comment by veksha** [comment]
maybe it's some scripting language/engine for Object Pascal?

**Comment by Alexey-T** [comment]
I don't what what is 'pax pascal' and cannot find it in web! I removed lex from 'registry'.
