### ISSUE TITLE
How to change the background and hide the dots?

### ISSUE THREAD

**Issue by eltonfabricio10** [veksha/cuda_exterminal#38]
![Screenshot_20220918_221449](https://user-images.githubusercontent.com/25956396/190936670-e0c1b740-6754-49f3-8699-e95286cbf778.png)

**Comment by veksha** [comment]
Hi.
I have disabled showing of unprinted chars.
commit: https://github.com/veksha/cuda_exterminal/commit/ba41f2f01326ad9c89250432cc8e4ab87abd49cf

colors are hardcoded inside `memoscreen.py` file:

![image](https://user-images.githubusercontent.com/275333/190953011-a9e5fbfe-a553-406a-88fd-25665b792888.png)

I could add an option to change colors from config file in the future.

**Comment by eltonfabricio10** [comment]
Is it too hard to take the editor background color and add it to the terminal background?

**Comment by veksha** [comment]
@eltonfabricio10 
added new option "themed". please, test.  commit: https://github.com/veksha/cuda_exterminal/commit/2fcbba2d73991c043e8a1a557815e33bd68885f0
grab new changes and set "themed" to "1" in ExTerminal config section.

@Alexey-T, you can test it too.
@Alexey-T, also I noticed that `APPSTATE_THEME_UI` is not documented here https://wiki.freepascal.org/CudaText_API. is it OK?

**Comment by Alexey-T** [comment]
wiki has
```
on_state(self, ed_self, state): Called after some app state is changed. Param "state" is one of APPSTATE_nnnn constants. ed_self is None.
on_state_ed(self, ed_self, state): Called after some editor state is changed. Param "state" is one of EDSTATE_nnnn constants.
```
I did not document all values.

**Comment by Alexey-T** [comment]
veksha, 'themed' work good for me.

**Comment by eltonfabricio10** [comment]
Thanks, my friend

**Comment by veksha** [comment]
no problem
