### ISSUE TITLE
How to increase font size?

### ISSUE THREAD

**Issue by eltonfabricio10** [veksha/cuda_exterminal#39]
Is it possible to be the same size as the output panel?

**Comment by veksha** [comment]
I can read "font_size" option from app config. Output/Console panels reading it too, i guess.

**Comment by veksha** [comment]
done: https://github.com/veksha/cuda_exterminal/commit/f960b0fb4a3ab7cbb87efead668cb75614b13521
please test, @eltonfabricio10.

**Comment by eltonfabricio10** [comment]
It's works! Thanks!
