### ISSUE TITLE
Background of the icon

### ISSUE THREAD

**Issue by eltonfabricio10** [veksha/cuda_exterminal#40]
[Here](https://github.com/veksha/cuda_exterminal/blob/fd21b0076f67502d27389415f7a8546a23f75ed3/terminal.py#L65) it is defined as "TabBg". However, I think it's better "SideBadgeBg"

What do you think @veksha?

**Comment by Alexey-T** [comment]
this must reuse the var, please
```
            'color': app_proc(PROC_THEME_UI_DICT_GET, '')['TabBg']['color'],
...
            'font_color': app_proc(PROC_THEME_UI_DICT_GET, '')['TabFont']['color'],
```

**Comment by veksha** [comment]
you are talking about header colors?
changed locally to `SideBadgeFont`/`SideBadgeBg`, hmm.....

@eltonfabricio10, I think it could be too sticking with blue (or green!) color.

![image](https://user-images.githubusercontent.com/275333/192155357-0d2f26b4-8e38-4e00-ab9d-7eafaa42b8e7.png)

@Alexey-T, 
> reuse the var, please

Hi, Alexey. please, clarify.
what we can reuse if we MUST call `app_proc` everytime on theme change?

BTW, `SideBadgeFont` in some themes must be fixed, i think:
themes: "brackets (light)", "green"

![image](https://user-images.githubusercontent.com/275333/192155677-e4cbc371-0111-4fd8-8dfe-2e4a9a86a688.png)
![image](https://user-images.githubusercontent.com/275333/192155602-abef7cc2-10a0-4488-952e-78be8e7570f1.png)

**Comment by Alexey-T** [comment]
use var here:

```
            theme = app_proc(PROC_THEME_UI_DICT_GET, '')
...            
            'color': theme['TabBg']['color'],
...
            'font_color': theme['TabFont']['color'],
```

**Comment by Alexey-T** [comment]
>BTW, SideBadgeFont in some themes must be fixed, i think:
themes: "brackets (light)", "green"

but that theme item works good for sidebar badges, no? just don't use it for terminal caption.

**Comment by veksha** [comment]
> but that theme item works good for sidebar badges, no

colors are the same for badges.

**Comment by veksha** [comment]
> use var here to store app_proc() result:

oh. yes. you mean this: https://github.com/veksha/cuda_exterminal/commit/5ba039f98295a53b91b2ee642e515281fcf6fcd1

**Comment by veksha** [comment]
@Alexey-T, do you use ExTerminal with `show_caption=1`? what can you say about colors? (`TabBg` vs `SideBadgeBg`)

**Comment by Alexey-T** [comment]
fixed 2 items in theme 'green'. about 'brackets'-- will fix later.

**Comment by Alexey-T** [comment]
> @Alexey-T, do you use ExTerminal with `show_caption=1`? 

no

>what can you say about colors? (`TabBg` vs `SideBadgeBg`)

new variant is not good. old is good.

**Comment by veksha** [comment]
@eltonfabricio10, I think old variant is good too.

**Comment by eltonfabricio10** [comment]
My idea is to change the background color of the terminal icon
![Screenshot_20220925_144556](https://user-images.githubusercontent.com/25956396/192157556-3f59a91a-9e62-4432-9643-b01f8296da83.png)

**Comment by Alexey-T** [comment]
this BG must be transparent. if not - it will look badly.

**Comment by veksha** [comment]
> My idea is to change the background color of the terminal icon ![Screenshot_20220925_144556](https://user-images.githubusercontent.com/25956396/192157556-3f59a91a-9e62-4432-9643-b01f8296da83.png)

ExTerminal code is not changing it, I don't know how to change it and why.

**Comment by eltonfabricio10** [comment]
Sorry, it was my mistake

**Comment by veksha** [comment]
every theme has different background color for icon:
![image](https://user-images.githubusercontent.com/275333/192160039-f9a6cae3-6a71-4ce5-a0dd-ef1b1e604fb3.png)
![image](https://user-images.githubusercontent.com/275333/192160047-9ec3c327-f191-4fa1-b150-edc7d35bebb0.png)
![image](https://user-images.githubusercontent.com/275333/192160052-31947eb3-8a8e-4dcc-9c90-410ace7e255a.png)

it's not ExTerminal issue.

**Comment by eltonfabricio10** [comment]
Yes, but it was good to improve the code and congratulations for the plugin

**Comment by veksha** [comment]
yes. thank you.
