### ISSUE TITLE
context menu item 'Close terminal' 

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_exterminal#41]
maybe disable the menuitem (`menu_proc()` can disable items) if called on the initial plugin sidebar icon?

**Comment by veksha** [comment]
done: https://github.com/veksha/cuda_exterminal/commit/4aaf4d477d02b4db170e4bb0b03bbcb8492bc13e
works ok?

**Comment by Alexey-T** [comment]
yes, ok
