### ISSUE TITLE
Clean the entire terminal

### ISSUE THREAD

**Issue by eltonfabricio10** [veksha/cuda_exterminal#42]
Currently the clear command (Linux) does not clean the terminal completely.

![Peek 29-09-2022 09-30](https://user-images.githubusercontent.com/25956396/193031932-22cf4b07-e129-46bf-9375-0263c7957404.gif)

**Comment by Alexey-T** [comment]
@veksha I confirm this.

**Comment by Alexey-T** [comment]
add to history:
```
2022.10.03
- fix: "clear" command did not clear all lines
```

**Comment by veksha** [comment]
fixed more and added txt to history.
thanks. is it works OK?

**Comment by Alexey-T** [comment]
yes, OK now.

**Comment by Alexey-T** [comment]
history. wrong date
```
2022.10.03
- fix: "clear" command
```

**Comment by veksha** [comment]
fixed

**Comment by eltonfabricio10** [comment]
Thanks my friend
