### ISSUE TITLE
terminal shows 'margin' line like main editor

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_exterminal#45]
![Screenshot from 2022-10-30 11-23-41](https://user-images.githubusercontent.com/4154978/198869317-210b1b43-6768-49ff-8bd8-0b62fadcc13f.png)

**Comment by Alexey-T** [comment]
ed.set_prop(PROP_MARGIN, 2000)

**Comment by veksha** [comment]
added to history too
