### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by eltonfabricio10** [veksha/cuda_exterminal#46]
![Peek 06-11-2022 20-57](https://user-images.githubusercontent.com/25956396/200202746-e7dd2399-0916-4320-8fe1-3ef2c4383aa1.gif)

When clicking on a terminal, it opens more two

**Comment by eltonfabricio10** [comment]
Sorry, I updated another plugin and forgot to restart Cud
No bugs :)

**Comment by veksha** [comment]
What plugin? Interesting

**Comment by eltonfabricio10** [comment]
Snippets
