### ISSUE TITLE
Constant 5% CPU usage under Windows

### ISSUE THREAD

**Issue by d0vgan** [veksha/cuda_exterminal#48]
Once ExTerminal's window is shown, CudaText starts to consume 5% of CPU. Even when the ExTerminal's window is closed, the CPU consumption remains 5%.
After looking into the code, I've seemed to identify the potential fix.
The method `run` of the `ControlTh` class contains a `while True` loop that calls `read()` again and again. I believe this is the source of the CPU usage. The logical fix is to introduce some delay when nothing has been read from the pipe:
```
if s:
    pass;    DEBUG_READ and print(s)
    self.add_buf(s)
else:
    sleep(0.05) # reduces CPU usage while doing nothing!
```
I tested it under Windows, and this simple fix reduced the CPU usage from 5% to 0.5%.

**Comment by veksha** [comment]
thank you! added your fix.
