### ISSUE TITLE
Command history?

### ISSUE THREAD

**Issue by d0vgan** [veksha/cuda_exterminal#49]
Does ExTerminal support command history? I tried Up/Down as well as Alt+Up/Alt+Down and Ctrl+Up/Ctrl+Down to get the previous/next command from the history - no luck. (I tried that under Windows).
In the same time, searching for a word "history" in the source code of the plugin creates an impression that there is a potential ability to have commands history.
Moreover, when I press PageUp/PageDown, I seem to get the very first and very last command from the command history.
How can I scroll through the command history in ExTerminal?

**Comment by veksha** [comment]
hi, @d0vgan , do you use cmd.exe? up/down is working for me fine.

**Comment by d0vgan** [comment]
Yes, cmd.exe, under Windows 10 Home 22H2, 64-bit.
When I press Up or Down in ExTerminal, nothing happens.
By the way, nothing happens also when there is some text and I press Left and Right - I was expecting the Left key to go to the previous character and the Right key to go to the next character.

**Comment by veksha** [comment]
@Alexey-T, can you repro this? arrow keys are working on my side. (Windows 11 Pro, 22H2 22621.525, 64-bit)

**Comment by veksha** [comment]
@d0vgan what keyboard do you have?

**Comment by d0vgan** [comment]
It's a Fujitsu LifeBook laptop with its built-in keyboard. I've never had any problems with this keyboard.

**Comment by veksha** [comment]
maybe we must replace OA, OB, OC, OD codes to [A, [B, [C, [D.
try it in terminal.py file:

```python
elif key == keys.VK_UP:
    self.write(ctrl.ESC+'[A')
    return False
elif key == keys.VK_DOWN:
    #print('markers',len(self.memo.attr(MARKERS_GET)))
    #print('markers',self.memo.attr(MARKERS_GET))
    self.write(ctrl.ESC+'[B')
    return False
elif key == keys.VK_RIGHT:
    self.write(ctrl.ESC+'[C')
    return False
elif key == keys.VK_LEFT:
    self.write(ctrl.ESC+'[D')
    return False
```

**Comment by veksha** [comment]
but according to this info, this may not work in Midnight Commander: https://stackoverflow.com/questions/46415660/what-code-does-midnight-commander-recognize-for-the-cursor-keys

**Comment by veksha** [comment]
but "OA, OB, OC, OD" should work.
please try to press ctrl/alt/ect keys to "unstuck" them or restart OS and try again.

**Comment by Alexey-T** [comment]
On Linux gtk2, 4 arrows work ok.
On Win10 x64 10.0.19044.2728, arrows don't work. and left/right arrows don't move caret over word. `shell_windows=cmd.exe`

**Comment by d0vgan** [comment]
> maybe we must replace OA, OB, OC, OD ansi codes to [A, [B, [C, [D. try it in terminal.py file:

Yes, this works!
So, maybe these ansi codes should be system-dependent? I.e. [A, [B, [C, [D for Windows and OA, OB, OC, OD otherwise? (The arrow keys works correctly under Mac with OA, OB, OC, OD).
By the way, I googled for escape codes, and could not find information related to e.g. ESC O A. From what I found so far, it looks like ESC O uses some "alternative character set", but I could not find additional info about that.

**Comment by veksha** [comment]
(i don't understand why it works fine on my Windows.)

still this needs to be fixed.
i found some info:

```
VT terminals themselves have two schemes of input, normal mode and application mode that can be switched by the application.

setappl DECCKM        Set cursor key to application          ^[[?1h
setcursor DECCKM      Set cursor key to cursor               ^[[?1l

DECCKM—Cursor Keys Mode
This control function selects the sequences the arrow keys send. You can use the four arrow keys to move the cursor through the current page or to send special application commands.

Default: Cursor
```

so if I understand correctly, by default we must send `[A`,
but if application switches Cusor Keys Mode to "Application mode", we must send `OA`.

I guess for now I will do "easy fix" by replacing OA to [A, ...
and when i get to linux and midnight commander i will do a proper fix.

**Comment by veksha** [comment]
done: https://github.com/veksha/cuda_exterminal/commit/0e3f36f02a4b7174f3b8e39c709082953f8cdeaf
