### ISSUE TITLE
suggested plg name

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_exterminal#5]
Terminal Advanced
Terminal Ultra
Terminal Ex

**Comment by veksha** [comment]
![image](https://user-images.githubusercontent.com/275333/176908312-611b69af-beba-4c61-9c41-539bbcce439a.png)

simpler plugin
advanced plugin
advanced ex plugin
advanced utlra plugin
😆

**Comment by veksha** [comment]
ExTerminal

**Comment by Alexey-T** [comment]
Ok, please go on and rename at everywhere (and name of config file)

**Comment by veksha** [comment]
done
