### ISSUE TITLE
[Not An Issue][Advice Needed] PseudoConsole Escape Codes

### ISSUE THREAD

**Issue by d0vgan** [veksha/cuda_exterminal#51]
Let me ask you for advice, please.
Basing on the code of your plugin and on the article mentioned below, I tried to use the PseudoConsole technique in C++ code (under Windows 10). The article is:
https://learn.microsoft.com/en-us/windows/console/creating-a-pseudoconsole-session

I seemed to follow everything that you do in your Python code, as well as in the code from the mentioned article, but the actual result that I read from the PseudoConsole by ReadFile() is unexpectedly full of Escape Codes. For example:
```
awk --version
[2J[m[Ha]0;C:\tools\awk\awk.exe[?25hwk version 20121220

tcc --version
[2J[m[Htcc: error: invalid option -- '--version'
]0;C:\tools\tcc\tcc.exe[?25h
```

As far as I can see, these unreadable characters correspond to the `ESC [ ...` and `ESC ] ...` Escape Codes. I have no idea why they are read by ReadFile() and how can I get rid of them.

As your plugin's output does not contain anything like this, I'm hoping you might give me some hint if you faced something similar during development? And if you did, how have you fixed that?

**Comment by d0vgan** [comment]
The code where I'm trying to deal with the PseudoConsole is here:
https://github.com/d0vgan/nppexec/blob/feature/pseudo-console/NppExec/src/NppExec.cpp#L3346
https://github.com/d0vgan/nppexec/blob/feature/pseudo-console/NppExec/src/NppExecCommandExecutor.h#L64

**Comment by veksha** [comment]
Hi @d0vgan 

> is unexpectedly full of Escape Codes

unexpectedly? there is no other way to work with PseudoConsole.
in ExTerminal I use `pyte` library to decode incoming Escape Codes.

form your link https://learn.microsoft.com/en-us/windows/console/creating-a-pseudoconsole-session: 
![image](https://user-images.githubusercontent.com/275333/230202418-4fe16365-7c21-48ed-ad35-1c69ccac0440.png)

**Comment by veksha** [comment]
for example, you parse the stream and got Escape Code that tells you to clear your screen, you must do it on your GUI.
another Escape Code will tell you to position "cursor" to screen center, once again you must do the same in your GUI.
if after that comes plain text - just draw it on current cursor position.

maybe this library will help you: https://github.com/KazDragon/terminalpp
i don't know.

**Comment by d0vgan** [comment]
Thank you very much for your clarifications!
